config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    confirmations: 'customers/confirmations',
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :producers, controllers: {
    confirmations: 'producers/confirmations',
    sessions:      'producers/sessions',
    passwords:     'producers/passwords',
    registrations: 'producers/registrations'
  }
  root to: "introductions#index"
  resources :producers, only: :show
  resources :products do
    collection do
      get 'search'
    end
  end
  
end

app/views/shared/_customer_header.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to "TSUNAGU", products_path, class: :logo %>
      </div>
      <div class="nav__right">
        <em class="current__name">ようこそ！<br/>
          <b><%= current_customer.customer_name %></b>さん
        </em>
        <div class="btn__pro">
          <%=link_to "商品一覧", products_path, class: :nav__btn %>
        </div>
        <div class="btn__pro">
          <%=link_to "買い物かご", "#", class: :nav__btn %>
        </div>
        <div class="btn__pro">
          <%=link_to "アカウント", "#", class: :nav__btn %>
        </div>
        <div class="btn__pro">
          <%=link_to "ログアウト", destroy_customer_session_path, method: :delete, class: :nav__btn %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p class="copyright">Copyright © TUNAGU All rights reserved.</p>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to "TSUNAGU", root_path, class: :logo %>
      </div>
      <div class="nav__right">
        <div class="btn__pro">
          <% if producer_signed_in? %>
            <em><b><%= current_producer.farm_name %></b>さん</em><br/>
            <%= link_to "ログアウト", destroy_producer_session_path, method: :delete, class: :nav__btn %>
          <% else %>
            <em><b>生産者</b>の</em><br/>
            <%= link_to "ログイン", new_producer_session_path, class: :nav__btn %>
          <% end %>
        </div>
        <div class="btn__pro">
          <% if customer_signed_in? %>
            <em><b><%= current_customer.customer_name %></b>さん</em><br/>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: :nav__btn %>
          <% else %>
            <em><b>購入者</b>の</em><br/>
            <%= link_to "ログイン", new_customer_session_path, class: :nav__btn %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_product_header.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to "TSUNAGU", producer_path(current_producer.id), class: :logo %>
      </div>
      <div class="nav__right">
        <em class="current__name">ようこそ！<br/>
          <b><%= current_producer.farm_name %></b>さん
        </em>
        <div class="btn__pro">
          <%=link_to "商品一覧", producer_path(current_producer.id), class: :nav__btn %>
        </div>
        <div class="btn__pro">
          <%=link_to "商品登録", new_product_path, class: :nav__btn %>
        </div>
        <div class="btn__pro">
          <%=link_to "アカウント", "#", class: :nav__btn %>
        </div>
        <div class="btn__pro">
          <%=link_to "ログアウト", destroy_producer_session_path, method: :delete, class: :nav__btn %>
        </div>
      </div>
    </div>
  </div>
</header>