config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    confirmations: 'customers/confirmations',
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :producers, controllers: {
    confirmations: 'producers/confirmations',
    sessions:      'producers/sessions',
    passwords:     'producers/passwords',
    registrations: 'producers/registrations'
  }
  root to: "introductions#index"
  resources :producers, only: :show
  resources :products do
    collection do
      get 'search'
    end
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :capacity
  belongs_to :main_product
  belongs_to :producer
  has_one_attached :image
  

  with_options presence: true do
    validates :name
    validates :image
    validates :price
    validates :capacity_id
    validates :main_product_id
    validates :features
  end

  validates_format_of :price, with: /\A[0-9]+\z/, message: '半角数値で入力してください'
  validates_numericality_of :price, only_integer: true, greater_than_or_equal_to: 10, less_than_or_equal_to: 999_999,
                                    message: '決められた数値の範囲内で入力してください'


  with_options numericality: { other_than: 0, message: 'を選択してください' } do
    validates :capacity_id
    validates :main_product_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_producer!, except: %i[ index search show ]
  before_action :move_to_producers_show, only: %i[ edit update destroy ]
  before_action :search_product, only: %i[ index search ]

  def index
    @products = Product.includes(:producer).page(params[:page]).per(18).order('updated_at DESC')
    set_product_column
    unless current_customer
      redirect_to root_path
    end
  end

  def search
    @results = @p.result.includes(:producer).page(params[:page]).per(18).order('updated_at DESC')
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to producer_path(current_producer.id)
    else
      render :new
    end
  end

  def show
    unless current_customer || @product.producer == current_producer
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to producer_path(current_producer.id)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to producer_path(current_producer.id)
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:image, :name, :price, :capacity_id, :main_product_id, :features).merge(producer_id: current_producer.id)
    end

    def move_to_producers_show 
      unless @product.producer == current_producer
        redirect_to producer_path(current_producer.id)
      end
    end
    
    def search_product
      @p = Product.ransack(params[:q])
    end

    def set_product_column
      @product_name = Product.select("name").distinct
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="card">
  <%= link_to image_tag(product.image.variant(resize: '324x217'), class: :card__img ), product_path(product.id) %>
  <div class="card__body">
    <%= link_to "#{product.name}", product_path(product.id), class: :card__title %>
    <% if customer_signed_in? %>
      <%= link_to "#{product.producer.farm_name}", producer_path(product.producer_id) , class: :card__name %>
    <% end %>
    <p class="card__summary">
      <%= "#{product.price}円" %><%= "#{product.capacity.name}" %>
    </p>
    <div class="page__btn">
      <%= link_to 'この商品の詳細ページへ', product, class: :link__btn%>
      <% if producer_signed_in? %>
        <% if current_producer.id == product.producer_id %>
          | <%= link_to "編集する", edit_product_path(product.id), class: :link__btn%>
          | <%= link_to '削除', product_path(product.id), method: :delete, class: :link__btn %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render "shared/product_header" %>
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">商品(生産物)情報の編集</h2>

      <%= form_with(model: @product, local: true) do |f| %>
        <%= render 'shared/error_messages', model: f.object %>

        <div class="field">
          <%= f.label :name, "商品(生産品)の名前" %>
          <%= f.text_field :name, class: "form__field", id:"product_name", placeholder: "例)トマト", maxlength: "40" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :image, "商品(生産品)の画像" %>
          <%= f.file_field :image, class: "image__field", id:"product_image" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :price, "価格設定" %>
          <%= f.number_field :price, id:"product_price", placeholder:"例) 10 〜 999,999 まで" %>円
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :capacity_id, "単位価格表示" %>
          <%= f.collection_select(:capacity_id, Capacity.all, :id, :name, {}, {class:"select-box"}) %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :main_product_id, "商品(生産品)の種類" %>
          <%= f.collection_select(:main_product_id, MainProduct.all, :id, :name, {}, {class:"select-box"}) %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :features, "商品(生産品)のご紹介文" %>
          <%= f.text_area :features, class: :form__text, id:"product_features", placeholder: "例) トマトの甘みとコクを最大限に引き出すために、トマトの生育に最適な環境を作って育てました！濃厚な味わいです！" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="actions">
          <%= f.submit "更新する", class: :form__btn  %>
        </div>
      <% end %>
        
      <%= link_to '詳細ページへ', @product, class: :link__btn %> |
      <%= link_to '一覧へ戻る', producer_path(current_producer.id), class: :link__btn %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/products/index.html.erb
<%= render "shared/customer_header" %>
<main class="main">
  <div class="inner">
    <h2 class="page-heading">
      <%= "登録商品(生産品)の一覧" %>
    </h2>
    <div class="search__wrapper">
      <%= search_form_for @p, url: search_products_path do |f| %>
        <div class="search_field">
          <%= f.label :name_or_features_or_producer_farm_name_cont, 'キーワードから探す' %>
          <%= f.search_field :name_or_features_or_producer_farm_name_cont, placeholder: "例)農園名、商品名など", class: "keyword__field" %>
        </div>
        <div class="search_field">
          <%= f.label :name_eq, '登録商品名(生産品名)' %>
          <%= f.collection_select(:name_eq, @product_name, :name, :name, {include_blank: '指定なし'}, {class: "search__box"}) %>
        </div>
        <div class="search_field">
          <%= f.label :main_product_id_eq, '商品(生産品)の種類' %>
          <%= f.collection_select(:main_product_id_eq, MainProduct.all, :id, :name, {include_blank: '指定なし'}, {class: "search__box"}) %>
        </div>
        <div class="search_field">
          <%= f.label :price, '価格' %>
          <%= f.number_field :price_gteq, class: "keyword__number", placeholder: "下限)10" %>円 以上 〜
          <%= f.number_field :price_lteq, class: "keyword__number", placeholder: "上限)999999" %>円 以下
        </div>
        <div class="actions">
          <%= f.submit '検索', class: :form__btn %>
        </div>
      <% end %>
    </div>
    <div class="card__wrapper">
      <%= render partial: "product", collection: @products %>
    </div>
    <div class="paginate">
      <%= paginate @products %>
    </div>
  </div>
</main>
<%= render "shared/footer" %>

app/views/products/new.html.erb
<%= render "shared/product_header" %>
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">商品(生産物)の新規登録</h2>

      <%= form_with(model: @product, local: true) do |f| %>
        <%= render 'shared/error_messages', model: f.object %>

        <div class="field">
          <%= f.label :name, "商品(生産品)の名前" %>
          <%= f.text_field :name, class: "form__field", id:"product_name", placeholder: "例)トマト", maxlength: "40" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :image, "商品(生産品)の画像" %>
          <%= f.file_field :image, class: "image__field", id:"product_image" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :price, "価格設定" %>
          <%= f.number_field :price, class: "number__field", id:"product_price", placeholder:"例) 10 〜 999,999 まで" %>円
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :capacity_id, "単位価格表示" %>
          <%= f.collection_select(:capacity_id, Capacity.all, :id, :name, {}, {class:"select-box"}) %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :main_product_id, "商品(生産品)の種類" %>
          <%= f.collection_select(:main_product_id, MainProduct.all, :id, :name, {}, {class:"select-box"}) %>
          <span class="indispensable">必須</span>
        </div>

        <div class="field">
          <%= f.label :features, "商品(生産品)のご紹介文" %>
          <%= f.text_area :features, class: :form__text, id:"product_features", placeholder: "例) トマトの甘みとコクを最大限に引き出すために、トマトの生育に最適な環境を作って育てました！濃厚な味わいです！" %>
          <span class="indispensable">必須</span>
        </div>

        <div class="actions">
          <%= f.submit "新規登録", class: :form__btn  %>
        </div>
      <% end %>
        
      <%= link_to '戻る', producer_path(current_producer.id), class: :link__btn %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/products/search.html.erb
<%= render "shared/customer_header" %>
<main class="main">
  <div class="inner">
    <h2 class="page-heading">
      <%= "商品の検索結果一覧" %>
    </h2>
    <table class="sort__table">
      <thead>
        <tr>
          <th>表示順:</th>
          <th><%= sort_link(@p, :created_at, "登録日時") %></th>
          <th><%= sort_link(@p, :updated_at, "更新日時") %></th>
          <th><%= sort_link(@p, :name, "商品名(生産品)") %></th>
          <th><%= sort_link(@p, :main_product_id, "生産品の種類") %></th>
          <th><%= sort_link(@p, :producer_id, "生産者名(農園名)") %></th>
          <th colspan="5"></th>
        </tr>
      </thead>
    </table>
    <div class="card__wrapper">
      <% if @results.length !=0 %>
        <%= render partial: "product", collection: @results %>
      <% else %>
        該当する商品はありません
      <% end %>
    </div>
    <div class="paginate">
      <%= paginate @results %>
    </div>
  </div>
</main>
<%= render "shared/footer" %>

app/views/products/show.html.erb
<% if current_producer %>
  <%= render "shared/product_header" %>
<% else %>
  <%= render "shared/customer_header" %>
<% end %>
<main class="main">
  <div class="inner">
    <div class="product__wrapper">
      <p class="product__hedding">
        <%= @product.name %>
      </p>
      <% if current_producer == @product.producer %>
        <div class="product__manage">
          <%= link_to "編集する", edit_product_path(@product.id), class: :product__btn %>
          <%= link_to "削除する", product_path(@product.id), method: :delete, class: :product__btn %>
        </div>
      <% end %>
      <div class="product__image">
        <%= image_tag @product.image %>
      </div>
      <div class="product__body">
        <div class="product__detail">
          <p class="detail__title">商品の価格/単位価格表示</p>
          <p class="detail__message">
            <%= "#{@product.price}円" %><%= @product.capacity.name %>
          </p>
        </div>
        <div class="product__detail">
          <p class="detail__title">商品(生産品)の種類</p>
          <p class="detail__message">
            <%= @product.main_product.name %>
          </p>
        </div>
        <div class="product__detail">
          <p class="detail__title">商品(生産品)のご紹介文</p>
          <p class="detail__message">
            <%= "「#{@product.features}」" %>
          </p>
        </div>
        <% if customer_signed_in? %>
          <div class="product__detail">
            <p class="detail__title">生産者の名前(農園名)</p>
            <p class="detail__message">
              <%= link_to "#{@product.producer.farm_name}", producer_path(@product.producer_id), class: :"link__btn" %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>
<%= render "shared/footer" %>